import type { Metadata } from 'next'
import { useState } from 'react'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section style={{ height: '100vh' }}>
            {/* <ErrorBoundary></ErrorBoundary> */}

            <h1>为什么有一些乱七八糟的东西</h1>
            {children}</section>

    )
}
