import { log } from 'console'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { message } from 'antd'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   const a = () => {
//     console.log(888)
//     console.log(children)
//     return <>22</>
//   }
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}
//         {a()}
//       </body>
//     </html>
//   )
// }
export default async function RootLayout({
  comfireModal,
  children
}: {
  // ...
  comfireModal: React.ReactNode
  children: React.ReactNode
}) {
  return (
    <>
      {/* ... */}
      <html lang="en">
        <body className={inter.className}>
          <div>{comfireModal}</div>
          <div>{children}</div>
        </body>
      </html>

    </>
  )
}